using System;
using System.Collections.Generic;

namespace Library.DataAccessLayer.Models
{
    public partial class Tbcandium
    {
        public string? Maqd { get; set; }
        public string? Tenphuongtien { get; set; }
        public string? Kieu { get; set; }
        public string? So { get; set; }
        public string? Capchinhxac { get; set; }
        public string? Mucmax { get; set; }
        public string? Mucmin { get; set; }
        public string? Donvisd { get; set; }
        public string? Chedokd { get; set; }
        public string? Ngay { get; set; }
        public string? Kiemdinhvien { get; set; }
        public string? Max1 { get; set; }
        public string? D1 { get; set; }
        public string? E1 { get; set; }
        public string? Max2 { get; set; }
        public string? D2 { get; set; }
        public string? E2 { get; set; }
        public string? Max3 { get; set; }
        public string? D3 { get; set; }
        public string? E3 { get; set; }
        public string? Max4 { get; set; }
        public string? D4 { get; set; }
        public string? E4 { get; set; }
        public string? Diachisd { get; set; }
        public string? Ppthuchien { get; set; }
        public string? Dkmt { get; set; }
        public string? NamSx { get; set; }
        public string? NuocSx { get; set; }
        public string? Muccan { get; set; }
        public string? Chuantb { get; set; }
        public int? Ktnhan { get; set; }
        public int? Ktdaydu { get; set; }
        public int? Ktdongho { get; set; }
        public int? Ktchitiet { get; set; }
        public string? Mtmucmin { get; set; }
        public string? Imucmin { get; set; }
        public string? Gmucmin { get; set; }
        public string? Saisoe0mucmin { get; set; }
        public string? Sscpmucmin { get; set; }
        public string? Mil1dd { get; set; }
        public string? Nmxl1dd { get; set; }
        public string? Layrannmin { get; set; }
        public string? Layrannnuamax { get; set; }
        public string? Layrannmax { get; set; }
        public string? I2min { get; set; }
        public string? I2nuamax { get; set; }
        public string? I2max { get; set; }
        public string? I2ti1 { get; set; }
        public string? I2ti1nuamax { get; set; }
        public string? I2ti1max { get; set; }
        public string? Themvao1p10dmin { get; set; }
        public string? Themvao1p10dnuamax { get; set; }
        public string? Themvao1p10dmax { get; set; }
        public string? Themvao1p4dmin { get; set; }
        public string? Themvao1p4dnuamax { get; set; }
        public string? Themvao1p4dmax { get; set; }
        public string? I1nuamaxll { get; set; }
        public string? I2nuamaxll { get; set; }
        public string? I3nuamaxll { get; set; }
        public string? I4nuamaxll { get; set; }
        public string? I5nuamaxll { get; set; }
        public string? I6nuamaxll { get; set; }
        public string? Delta1nuamax { get; set; }
        public string? Delta2nuamax { get; set; }
        public string? Delta3nuamax { get; set; }
        public string? Delta4nuamax { get; set; }
        public string? Delta5nuamax { get; set; }
        public string? Delta6nuamax { get; set; }
        public string? P1nuamaxll { get; set; }
        public string? P2nuamaxll { get; set; }
        public string? P3nuamaxll { get; set; }
        public string? P4nuamaxll { get; set; }
        public string? P5nuamaxll { get; set; }
        public string? P6nuamaxll { get; set; }
        public string? I1maxll { get; set; }
        public string? I2maxll { get; set; }
        public string? I3maxll { get; set; }
        public string? I4maxll { get; set; }
        public string? I5maxll { get; set; }
        public string? I6maxll { get; set; }
        public string? Delta1maxll { get; set; }
        public string? Delta2maxll { get; set; }
        public string? Delta3maxll { get; set; }
        public string? Delta4maxll { get; set; }
        public string? Delta5maxll { get; set; }
        public string? Delta6maxll { get; set; }
        public string? P1maxll { get; set; }
        public string? P2maxll { get; set; }
        public string? P3maxll { get; set; }
        public string? P4maxll { get; set; }
        public string? P5maxll { get; set; }
        public string? P6maxll { get; set; }
        public string? Pimaxmin { get; set; }
        public string? Sscpnuamax { get; set; }
        public string? Pjmaxmin { get; set; }
        public string? Sscpmax { get; set; }
        public string? Muctailt { get; set; }
        public string? Glt { get; set; }
        public string? L1lt { get; set; }
        public string? L2lt { get; set; }
        public string? L3lt { get; set; }
        public string? L4lt { get; set; }
        public string? Deltaglt { get; set; }
        public string? Delta1lt { get; set; }
        public string? Delta2lt { get; set; }
        public string? Delta3lt { get; set; }
        public string? Delta4lt { get; set; }
        public string? Ssglt { get; set; }
        public string? Ss1lt { get; set; }
        public string? Ss2lt { get; set; }
        public string? Ss3lt { get; set; }
        public string? Ss4lt { get; set; }
        public string? Ecglt { get; set; }
        public string? Ec1lt { get; set; }
        public string? Ec2lt { get; set; }
        public string? Ec3lt { get; set; }
        public string? Ec4lt { get; set; }
        public string? Sscpg { get; set; }
        public string? Sscp1 { get; set; }
        public string? Sscp2 { get; set; }
        public string? Sscp3 { get; set; }
        public string? Sscp4 { get; set; }
        public string? Mxl1dd { get; set; }
        public string? A1 { get; set; }
        public string? A2 { get; set; }
        public string? A3 { get; set; }
        public string? A4 { get; set; }
        public string? A5 { get; set; }
        public string? A6 { get; set; }
        public string? A7 { get; set; }
        public string? A8 { get; set; }
        public string? A9 { get; set; }
        public string? A10 { get; set; }
        public string? A11 { get; set; }
        public string? A12 { get; set; }
        public string? A13 { get; set; }
        public string? A14 { get; set; }
        public string? A15 { get; set; }
        public string? A16 { get; set; }
        public string? A17 { get; set; }
        public string? A18 { get; set; }
        public string? A19 { get; set; }
        public string? A20 { get; set; }
        public string? B1 { get; set; }
        public string? B2 { get; set; }
        public string? B3 { get; set; }
        public string? B4 { get; set; }
        public string? B5 { get; set; }
        public string? B6 { get; set; }
        public string? B7 { get; set; }
        public string? B8 { get; set; }
        public string? B9 { get; set; }
        public string? B10 { get; set; }
        public string? B11 { get; set; }
        public string? B12 { get; set; }
        public string? B13 { get; set; }
        public string? B14 { get; set; }
        public string? B15 { get; set; }
        public string? B16 { get; set; }
        public string? B17 { get; set; }
        public string? B18 { get; set; }
        public string? B19 { get; set; }
        public string? B20 { get; set; }
        public string? C1 { get; set; }
        public string? C2 { get; set; }
        public string? C3 { get; set; }
        public string? C4 { get; set; }
        public string? C5 { get; set; }
        public string? C6 { get; set; }
        public string? C7 { get; set; }
        public string? C8 { get; set; }
        public string? C9 { get; set; }
        public string? C10 { get; set; }
        public string? C11 { get; set; }
        public string? C12 { get; set; }
        public string? C13 { get; set; }
        public string? C14 { get; set; }
        public string? C15 { get; set; }
        public string? C16 { get; set; }
        public string? C17 { get; set; }
        public string? C18 { get; set; }
        public string? C19 { get; set; }
        public string? C20 { get; set; }
        public string? G1 { get; set; }
        public string? G2 { get; set; }
        public string? G3 { get; set; }
        public string? G4 { get; set; }
        public string? G5 { get; set; }
        public string? G6 { get; set; }
        public string? G7 { get; set; }
        public string? G8 { get; set; }
        public string? G9 { get; set; }
        public string? G10 { get; set; }
        public string? G11 { get; set; }
        public string? G12 { get; set; }
        public string? G13 { get; set; }
        public string? G14 { get; set; }
        public string? G15 { get; set; }
        public string? G16 { get; set; }
        public string? G17 { get; set; }
        public string? G18 { get; set; }
        public string? G19 { get; set; }
        public string? G20 { get; set; }
        public string? H1 { get; set; }
        public string? H2 { get; set; }
        public string? H3 { get; set; }
        public string? H4 { get; set; }
        public string? H5 { get; set; }
        public string? H6 { get; set; }
        public string? H7 { get; set; }
        public string? H8 { get; set; }
        public string? H9 { get; set; }
        public string? H10 { get; set; }
        public string? H11 { get; set; }
        public string? H12 { get; set; }
        public string? H13 { get; set; }
        public string? H14 { get; set; }
        public string? H15 { get; set; }
        public string? H16 { get; set; }
        public string? H17 { get; set; }
        public string? H18 { get; set; }
        public string? H19 { get; set; }
        public string? H20 { get; set; }
        public string? I1 { get; set; }
        public string? I2 { get; set; }
        public string? I3 { get; set; }
        public string? I4 { get; set; }
        public string? I5 { get; set; }
        public string? I6 { get; set; }
        public string? I7 { get; set; }
        public string? I8 { get; set; }
        public string? I9 { get; set; }
        public string? I10 { get; set; }
        public string? I11 { get; set; }
        public string? I12 { get; set; }
        public string? I13 { get; set; }
        public string? I14 { get; set; }
        public string? I15 { get; set; }
        public string? I16 { get; set; }
        public string? I17 { get; set; }
        public string? I18 { get; set; }
        public string? I19 { get; set; }
        public string? I20 { get; set; }
        public string? K1 { get; set; }
        public string? K2 { get; set; }
        public string? K3 { get; set; }
        public string? K4 { get; set; }
        public string? K5 { get; set; }
        public string? K6 { get; set; }
        public string? K7 { get; set; }
        public string? K8 { get; set; }
        public string? K9 { get; set; }
        public string? K10 { get; set; }
        public string? K11 { get; set; }
        public string? K12 { get; set; }
        public string? K13 { get; set; }
        public string? K14 { get; set; }
        public string? K15 { get; set; }
        public string? K16 { get; set; }
        public string? K17 { get; set; }
        public string? K18 { get; set; }
        public string? K19 { get; set; }
        public string? K20 { get; set; }
        public string? L1 { get; set; }
        public string? L2 { get; set; }
        public string? L3 { get; set; }
        public string? L4 { get; set; }
        public string? L5 { get; set; }
        public string? L6 { get; set; }
        public string? L7 { get; set; }
        public string? L8 { get; set; }
        public string? L9 { get; set; }
        public string? L10 { get; set; }
        public string? L11 { get; set; }
        public string? L12 { get; set; }
        public string? L13 { get; set; }
        public string? L14 { get; set; }
        public string? L15 { get; set; }
        public string? L16 { get; set; }
        public string? L17 { get; set; }
        public string? L18 { get; set; }
        public string? L19 { get; set; }
        public string? L20 { get; set; }
        public string? M1 { get; set; }
        public string? M2 { get; set; }
        public string? M3 { get; set; }
        public string? M4 { get; set; }
        public string? M5 { get; set; }
        public string? M6 { get; set; }
        public string? M7 { get; set; }
        public string? M8 { get; set; }
        public string? M9 { get; set; }
        public string? M10 { get; set; }
        public string? M11 { get; set; }
        public string? M12 { get; set; }
        public string? M13 { get; set; }
        public string? M14 { get; set; }
        public string? M15 { get; set; }
        public string? M16 { get; set; }
        public string? M17 { get; set; }
        public string? M18 { get; set; }
        public string? M19 { get; set; }
        public string? M20 { get; set; }
        public string? N1 { get; set; }
        public string? N2 { get; set; }
        public string? N3 { get; set; }
        public string? N4 { get; set; }
        public string? N5 { get; set; }
        public string? N6 { get; set; }
        public string? N7 { get; set; }
        public string? N8 { get; set; }
        public string? N9 { get; set; }
        public string? N10 { get; set; }
        public string? N11 { get; set; }
        public string? N12 { get; set; }
        public string? N13 { get; set; }
        public string? N14 { get; set; }
        public string? N15 { get; set; }
        public string? N16 { get; set; }
        public string? N17 { get; set; }
        public string? N18 { get; set; }
        public string? N19 { get; set; }
        public string? N20 { get; set; }
    }
}
