using System;
using System.Collections.Generic;

namespace Library.DataAccessLayer.Models
{
    public partial class Tbdientim
    {
        public string? Maqd { get; set; }
        public string? Tenpt { get; set; }
        public string? Kieu { get; set; }
        public string? So { get; set; }
        public string? Namsx { get; set; }
        public string? Namsd { get; set; }
        public string? Noisx { get; set; }
        public string? Dtkythuat { get; set; }
        public string? Noisd { get; set; }
        public string? Qtkiemdinh { get; set; }
        public string? Ngaykd { get; set; }
        public string? Kiemdinhvien { get; set; }
        public string? Chedokiemdinh { get; set; }
        public string? Ssdienap1 { get; set; }
        public string? Ssdienap2 { get; set; }
        public string? Ssdienap3 { get; set; }
        public string? Ssdienapctkt { get; set; }
        public int? Ssdienapkl { get; set; }
        public string? Ssdonhay1 { get; set; }
        public string? Ssdonhay2 { get; set; }
        public string? Ssdonhay3 { get; set; }
        public string? Ssdonhayctkt { get; set; }
        public int? Ssdonhaykl { get; set; }
        public string? Ssthoigian1 { get; set; }
        public string? Ssthoigian2 { get; set; }
        public string? Ssthoigian3 { get; set; }
        public string? Ssthoigianctkt { get; set; }
        public int? Ssthoigiankl { get; set; }
        public string? Sstocdoghi1 { get; set; }
        public string? Sstocdoghi2 { get; set; }
        public string? Sstocdoghi3 { get; set; }
        public string? Sstocdoghictkt { get; set; }
        public int? Sstocdoghikl { get; set; }
        public string? Dotre1 { get; set; }
        public string? Dotre2 { get; set; }
        public string? Dotre3 { get; set; }
        public string? Dotrectkt { get; set; }
        public int? Dotrekl { get; set; }
        public string? Sstinhieuchuan1 { get; set; }
        public string? Sstinhieuchuan2 { get; set; }
        public string? Sstinhieuchuan3 { get; set; }
        public string? Sstinhieuchuanctkt { get; set; }
        public int? Sstinhieuchuankl { get; set; }
        public string? Ghiquamuc1 { get; set; }
        public string? Ghiquamuc2 { get; set; }
        public string? Ghiquamuc3 { get; set; }
        public string? Ghiquamucctkt { get; set; }
        public int? Ghiquamuckl { get; set; }
        public string? Hangsotg1 { get; set; }
        public string? Hangsotg2 { get; set; }
        public string? Hangsotg3 { get; set; }
        public string? Hangsotgctkt { get; set; }
        public int? Hangsotgkl { get; set; }
        public string? Tansobiendo1 { get; set; }
        public string? Tansobiendo2 { get; set; }
        public string? Tansobiendo3 { get; set; }
        public string? Tansobiendoctkt { get; set; }
        public int? Tansobiendokl { get; set; }
        public string? Trokhangvao1 { get; set; }
        public string? Trokhangvao2 { get; set; }
        public string? Trokhangvao3 { get; set; }
        public string? Trokhangvaoctkt { get; set; }
        public int? Trokhangvaokl { get; set; }
        public string? Ssdienapghi1 { get; set; }
        public string? Ssdienapghi2 { get; set; }
        public string? Ssdienapghi3 { get; set; }
        public string? Ssdienapghictkt { get; set; }
        public int? Ssdienapghikl { get; set; }
        public string? Hesonen1 { get; set; }
        public string? Hesonen2 { get; set; }
        public string? Hesonen3 { get; set; }
        public string? Hesonenctkt { get; set; }
        public int? Hesonenkl { get; set; }
        public string? Dorongdn1 { get; set; }
        public string? Dorongdn2 { get; set; }
        public string? Dorongdn3 { get; set; }
        public string? Dorongdnctkt { get; set; }
        public int? Dorongdnkl { get; set; }
        public string? Dotroidn1 { get; set; }
        public string? Dotroidn2 { get; set; }
        public string? Dotroidn3 { get; set; }
        public string? Dotroidnctkt { get; set; }
        public int? Dotroidnkl { get; set; }
        public string? Doontrong1 { get; set; }
        public string? Doontrong2 { get; set; }
        public string? Doontrong3 { get; set; }
        public string? Doontrongctkt { get; set; }
        public int? Doontrongkl { get; set; }
        public string? Hesoxa1 { get; set; }
        public string? Hesoxa2 { get; set; }
        public string? Hesoxa3 { get; set; }
        public string? Hesoxactkt { get; set; }
        public int? Hesoxakl { get; set; }
        public string? Dongdien1 { get; set; }
        public string? Dongdien2 { get; set; }
        public string? Dongdien3 { get; set; }
        public string? Dongdienctkt { get; set; }
        public int? Dongdienkl { get; set; }
        public string? Diachisd { get; set; }
        public string? Ddthuchien { get; set; }
    }
}
