using System;
using System.Collections.Generic;

namespace Library.DataAccessLayer.Models
{
    public partial class Trubom
    {
        public string? Tenpt { get; set; }
        public string? Maqd { get; set; }
        public string? Kieu { get; set; }
        public string? So { get; set; }
        public string? Capcx { get; set; }
        public string? Cssx { get; set; }
        public string? NamSx { get; set; }
        public string? Chedokd { get; set; }
        public string? Ngaykd { get; set; }
        public string? Luuluongnn { get; set; }
        public string? Luuluongln { get; set; }
        public string? Luongcptt { get; set; }
        public string? Cososd { get; set; }
        public string? Ppthuchien { get; set; }
        public string? Chuantb { get; set; }
        public string? Ddthuchien { get; set; }
        public int? Qsnhanhieu { get; set; }
        public int? Qsbophanchinh { get; set; }
        public int? Qskinhbaove { get; set; }
        public int? Qsongcaosu { get; set; }
        public int? Ktsobo { get; set; }
        public int? Ktdokin { get; set; }
        public int? Ktxoaso { get; set; }
        public int? Kttungat { get; set; }
        public string? Tgcapphat { get; set; }
        public string? Csthetich { get; set; }
        public string? Qmax { get; set; }
        public int? Klllln { get; set; }
        public string? VfdQmaxt1 { get; set; }
        public string? VfdQmaxt2 { get; set; }
        public string? VfdQmint1 { get; set; }
        public string? VfdQmint2 { get; set; }
        public string? VfdQmaxs1 { get; set; }
        public string? VfdQmaxs2 { get; set; }
        public string? VfdQmins1 { get; set; }
        public string? VfdQmins2 { get; set; }
        public string? VrefQmaxt1 { get; set; }
        public string? VrefQmaxt2 { get; set; }
        public string? VrefQmint1 { get; set; }
        public string? VrefQmint2 { get; set; }
        public string? VrefQmaxs1 { get; set; }
        public string? VrefQmaxs2 { get; set; }
        public string? VrefQmins1 { get; set; }
        public string? VrefQmins2 { get; set; }
        public string? EfdQmaxt1 { get; set; }
        public string? EfdQmaxt2 { get; set; }
        public string? EfdQmint1 { get; set; }
        public string? EfdQmint2 { get; set; }
        public string? EfdQmaxs1 { get; set; }
        public string? EfdQmaxs2 { get; set; }
        public string? EfdQmins1 { get; set; }
        public string? EfdQmins2 { get; set; }
        public string? EavQmaxt { get; set; }
        public string? EavQmaxs { get; set; }
        public string? EavQmint { get; set; }
        public string? EavQmins { get; set; }
        public string? Klqmaxt { get; set; }
        public string? Klqmaxs { get; set; }
        public string? Klqmint { get; set; }
        public string? Klqmins { get; set; }
        public string? Vfdtt { get; set; }
        public string? Vreftt { get; set; }
        public string? Ett { get; set; }
        public int? Kttachkhi { get; set; }
        public string? Qatachkhi { get; set; }
        public string? Vfdtk { get; set; }
        public string? Vreftk { get; set; }
        public string? Efdtk { get; set; }
        public string? Edtk { get; set; }
        public int? Kltk { get; set; }
        public string? Pfddt { get; set; }
        public string? Pprdt { get; set; }
        public string? Vfddt { get; set; }
        public string? Vprdt { get; set; }
        public string? Vrefdt { get; set; }
        public string? Efddt { get; set; }
        public string? Vfdtinhtien { get; set; }
        public string? Putt { get; set; }
        public string? Pctt { get; set; }
        public string? Pfdtt { get; set; }
        public string? Efptt { get; set; }
        public string? Kltt { get; set; }
        public string? Sochiong { get; set; }
        public int? Klong { get; set; }
        public string? Vfdin1 { get; set; }
        public string? Vfdin2 { get; set; }
        public string? Pfdin1 { get; set; }
        public string? Pfdin2 { get; set; }
        public string? Luonggnin1 { get; set; }
        public string? Luonggnin2 { get; set; }
        public string? Tienttin1 { get; set; }
        public string? Tienttin2 { get; set; }
        public string? Klin1 { get; set; }
        public string? Klin2 { get; set; }
        public int? Ktchucnangin { get; set; }
        public int? Ktnoidungin { get; set; }
        public int? Klchung { get; set; }
        public string? Diachisd { get; set; }
        public int? Klcptt { get; set; }
        public string? Kldttt { get; set; }
        public string? Kldtgt { get; set; }
        public string? Chatlongkd { get; set; }
        public int? Ktmat { get; set; }
        public string? Kiemdinhvien { get; set; }
    }
}
